name: Metrics
on:
  # Schedule updates daily
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing to master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Generate Overview Stats
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 05-guruprakash
          template: classic
          base: header, community, repositories, metadata
          filename: generated/overview.svg
          config_timezone: Asia/Kolkata

      # Step 2: Generate Language Stats
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 05-guruprakash
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          filename: generated/languages.svg
          config_timezone: Asia/Kolkata
